version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: storydb
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/admin"
      ME_CONFIG_SITE_BASEURL: "/"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    depends_on:
      - mongo

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
       sleep 5 &&
       ollama pull llama2 &&
       wait"

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: story-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - OLLAMA_URL=${OLLAMA_URL}
      - MODEL_NAME=${MODEL_NAME}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
    - ./backend:/app 
    - ./story_outputs:/app/story_outputs
    depends_on:
      - mongo
      - ollama

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: story-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api

volumes:
  mongo_data:
  ollama_data: